services:
  pokedexapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokedex-app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      NODE_ENV: prod
  db:
    image: mongo:5
    container_name: mongo-db
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: pokedex
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://mongo-db:27017/
    depends_on:
      - db
