services:
  db:
    image: mongo:5
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: pokedex
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - db
